url: https://maresmaggiosoftware.github.io
baseurl: 

# Site settings
title: Maggio Mares Software
email: MaggioMaresSoftware@gmail.com
description: "Create amazing websites alongside skilled professionals on a personal level. No robotic site generators here"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Angello Maggio
  pic: 1
  position: Full Stack Developer - Social Media Analyst
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Jonathan Mares
  pic: 2
  position: Dev Ops - Project Manager
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/maggiomares
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/maggiomares
  - title: bitbucket 
    url: http://bitbucket.org/maggiomaressoftware
  - title: github
    url: http://github.com/maggiomaressoftware

# Postal address (add as many lines as necessary)
address:
  - line: Sleepy Hollow, NY 10591
  - line: Tarrytown, NY 10591

# Build settings
markdown: kramdown
permalink: pretty